name: Web - CI - Test

on:
  push:
    branches:
      - master
    paths:
      - "apps/web/**"
    paths-ignore:
      - ".github/workflows/**"
      - "README.md"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "apps/web/**"

jobs:
  build:
    name: Web - Build and Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
